// This file was autogenerated by ../closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../authentication/scripts/app.js', ['authentication.App'], ['goog.object', 'goog.soy', 'templates.alerts', 'templates.footer', 'templates.menu']);
goog.addDependency('../../../authentication/scripts/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency('../../../authentication/scripts/templates.js', ['templates.alerts', 'templates.footer', 'templates.menu'], ['soy', 'soy.StringBuilder']);
