// This file was autogenerated by ../lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/scripts/common/ajax.js', ['common.ajax'], ['goog.Uri', 'goog.net.XhrManager', 'goog.soy']);
goog.addDependency('../../../../src/scripts/common/funcUtil.js', ['common.funcUtil'], []);
goog.addDependency('../../../../src/scripts/common/menu.js', ['common.menu'], ['common.ajax', 'goog.soy', 'templates.alerts', 'templates.menu']);
goog.addDependency('../../../../src/scripts/common/templates.js', ['templates.alerts', 'templates.footer', 'templates.menu'], ['soy', 'soy.StringBuilder']);
goog.addDependency('../../../../src/scripts/dto/storage_dto.js', ['dto.storage'], []);
goog.addDependency('../../../../src/scripts/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency('../../../../src/scripts/storage/app.js', ['storage.App'], ['common.ajax', 'common.menu', 'dto.storage', 'goog.dom.forms', 'goog.events.EventHandler', 'goog.object', 'goog.soy', 'storage.entry1', 'storage.entry2', 'templates.alerts', 'templates.footer', 'templates.storage']);
goog.addDependency('../../../../src/scripts/storage/box/app.js', ['storage.box.App'], ['common.ajax', 'common.menu', 'goog.dom.forms', 'goog.events.EventHandler', 'goog.object', 'goog.soy', 'storage.box.entry', 'templates.alerts', 'templates.footer', 'templates.storage']);
goog.addDependency('../../../../src/scripts/storage/box/entry.js', ['storage.box.entry'], ['common.ajax', 'common.funcUtil', 'goog.dom', 'goog.dom.forms', 'goog.dom.query', 'goog.events.EventHandler']);
goog.addDependency('../../../../src/scripts/storage/entry1.js', ['storage.entry1'], ['common.ajax', 'common.funcUtil', 'goog.dom', 'goog.dom.forms', 'goog.dom.query', 'goog.events.EventHandler']);
goog.addDependency('../../../../src/scripts/storage/entry2.js', ['storage.entry2'], ['common.ajax', 'common.funcUtil', 'goog.dom', 'goog.dom.forms', 'goog.dom.query', 'goog.events.EventHandler', 'goog.soy']);
goog.addDependency('../../../../src/scripts/storage/templates.js', ['templates.storage'], ['soy', 'soy.StringBuilder']);
goog.addDependency('../../../../src/scripts/top/app.js', ['top.App'], ['common.menu', 'goog.events.EventHandler', 'templates.alerts', 'templates.footer', 'templates.menu']);
